language: cpp

before_install:
  - sudo apt-get update
  - sudo apt-get install openjdk-7-jdk swig libboost-dev libboost-filesystem-dev libboost-test-dev

compiler:
  - gcc

before_script:
  - mkdir build
  - cd build
  - cmake ..
  - make

script: make test
