language: cpp

sudo: false

compiler:
  - gcc
  - clang

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - llvm-toolchain-precise-3.6
    packages:
    - gcc-5
    - g++-5
    - clang-3.6
    - openjdk-7-jdk
    - libboost-dev
    - libboost-filesystem-dev
    - libboost-test-dev
    - swig

before_script:
  - mkdir build
  - cd build
  - cmake ..
  - make

script: ./spec/libemojidex_spec --show_progress --log_level=all
