language: cpp

before_install:
  - sudo apt-get update -qq

install:
  - sudo apt-get install openjdk-8-jdk libboost-dev libboost-filesystem-dev libboost-test-dev swig

compiler:
  - gcc

before_script:
  - mkdir build
  - cd build
  - cmake ..
  - make

script: make test
