language: cpp

sudo: false

compiler:
  - gcc

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - llvm-toolchain-precise-3.6
    packages:
    - gcc-5
    - g++-5
    - openjdk-7-jdk
    - libboost-all-dev
    - swig

env: COMPILER=g++-5

before_script:
  - mkdir build
  - cd build
  - cmake ..
  - make

script: ./spec/libemojidex_spec --show_progress --log_level=all
