/******************************************************************************
 * emojidex client
 * Authors: Rei Kagetsuki
 * Copyright: Genshin Souzou Kabushiki Kaisha and Rei Kagetsuki 2015~
 * License: emojidex Open License
 *
 * This module provides full client access through the emojidex API
 * General usage documentation: http://developer.emojidex.com
 * *detailed documentation can be generated by doxygen and is bundled 
 * *with the c-emojidex repository.
 *****************************************************************************/
#ifndef _EMOJIDEX_CLIENT_H_
#define _EMOJIDEX_CLIENT_H_

#include "version.h"
#include "client/search.h"
#include <string>

namespace Emojidex {
	// Core client class (includes all components in a central state-machine client)
	class Client
	{
		public:
		Emojidex::SearchClient *search;

		Client();
		std::string version();
	}; // Client
} // Emojidex namespace

#endif // _EMOJIDEX_CLIENT_H_
